#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI-1-1 -d I II III IV V
# bspc monitor eDP-1 -d VI VII VIII IX X

bspc config border_radius        8
bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a yad-calendar state=floating focus=on

if [[ $(xrandr -q | grep "HDMI-1-0 connected") ]];
then
    xrandr --output eDP-1 --auto --output HDMI-1-0 --auto --left-of eDP-1
    bspc monitor HDMI-1-0 -d I II III IV V
    bspc monitor eDP-1 -d VI VII VIII IX X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar > /dev/null; do sleep1; done

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload example &
  done
else
  polybar --reload example &
fi

xsetroot -cursor_name left_ptr
